server {
    listen 8080;
    server_name localhost;
    client_max_body_size 1100M;
    
    error_page 301 www/errors/301.html;
    error_page 302 www/errors/302.html;
    error_page 400 www/errors/400.html;
    error_page 403 www/errors/403.html;
    error_page 404 www/errors/404.html;
    error_page 405 www/errors/405.html;
    error_page 411 www/errors/411.html;
    error_page 413 www/errors/413.html;
    error_page 500 www/errors/500.html;
    
    location / {
        methods GET POST DELETE;
        root www;
        index index.html;
        autoindex off;
    }
    
    location /files {
        methods GET DELETE;
        root www;
        index index.html;
        autoindex off;
    }
    
    location /listing_dir {
        methods GET;
        root www;
        autoindex on;
    }
    
    location /autoindex_test {
        methods GET;
        root www;
        autoindex on;
    }
    
    location /uploads {
        methods GET POST;
        root www;
        upload_path www/uploads;
    }
    
    location /delete_zone {
        methods GET DELETE;
        root www;
        autoindex off;
    }
    
    location /cgi-bin {
        methods GET POST;
        root cgi-bin;
        cgi .py /usr/bin/python3;
        cgi .php /usr/bin/php-cgi;
    }
    
    location /cgi {
        methods GET POST;
        root cgi-bin;
        cgi .py /usr/bin/python3;
        cgi .php /usr/bin/php-cgi;
    }
    
    location /test.txt {
        methods GET POST DELETE;
        root www;
    }
    
    location /redirect {
        redirect https://github.com/42;
    }
    
    location /redirect-local {
        redirect http://127.0.0.1:8080/;
    }
}

server {
    listen 9090;
    server_name server_two;
    client_max_body_size 1M;
    
    error_page 405 www/errors/405.html;
    error_page 413 www/errors/413.html;
    
    location / {
        methods GET;
        root www;
        index index.html;
        autoindex off;
    }
}
