server {
    listen 8080;
    server_name localhost;
    client_max_body_size 1100M;
    
    error_page 404 www/errors/404.html;
    error_page 403 www/errors/403.html;
    error_page 405 www/errors/405.html;
    error_page 500 www/errors/500.html;
    
    location / {
        methods GET POST DELETE;
        root www;
        index index.html;
        autoindex off;
    }
    
    location /files {
        methods GET DELETE;
        root www;
        autoindex off;
    }
    
    location /listing_dir {
        methods GET;
        root www;
        autoindex on;
    }
    
    location /uploads {
        methods GET POST;
        root www;
        upload_path www/uploads;
    }
    
    location /delete_zone {
        methods GET DELETE;
        root www;
    }
    
    location /cgi-bin {
        methods GET POST;
        root cgi-bin;
        cgi .py /usr/bin/python3;
        cgi .php /usr/bin/php-cgi;
    }
    
    location /cgi {
        methods GET POST;
        root cgi-bin;
        cgi .py /usr/bin/python3;
        cgi .php /usr/bin/php-cgi;
    }
}

server {
    listen 9090;
    server_name test_server;
    client_max_body_size 1M;
    
    location / {
        methods GET;
        root www;
        index index.html;
    }
}
