server
{
    listen 127.0.0.1:8080;
    root ./www_eval/site_a;
    index index.html;

    location /
    {
        allowed_methods GET;
    }
}

server
{
    listen 127.0.0.1:8081;
    root ./www_eval/site_b;
    index index.html;

    location /
    {
        allowed_methods GET;
    }
}
