server
{
    listen 127.0.0.1:8080;
    root ./www_eval/site_a;
    index index.html;
    client_max_body_size 1024;

    error_page 404 ./www_eval/site_a/errors/404.html;

    cgi .py /usr/bin/python3;

    location /
    {
        allowed_methods GET;
        autoindex off;
    }

    location /list
    {
        root ./www_eval/site_a/listing;
        allowed_methods GET;
        autoindex off;
    }

    location /with-index
    {
        root ./www_eval/site_a/with_index;
        index index.html;
        allowed_methods GET;
        autoindex off;
    }

    location /redirect-me
    {
        allowed_methods GET;
        redirect 301 /with-index/;
    }

    location /upload
    {
        root ./www_eval/site_a/uploads;
        allowed_methods GET POST;
        autoindex on;
        upload_enable on;
    }

    location /delete
    {
        root ./www_eval/site_a/uploads;
        allowed_methods GET DELETE;
        autoindex on;
    }

    location /post-only
    {
        root ./www_eval/site_a/uploads;
        allowed_methods POST;
        upload_enable on;
    }

    location /tiny-body
    {
        root ./www_eval/site_a/uploads;
        allowed_methods POST;
        upload_enable on;
        max_body_size 16;
    }

    location /cgi-bin
    {
        root ./www_eval/site_a/cgi-bin;
        allowed_methods GET POST;
        autoindex off;
        cgi .py /usr/bin/python3;
    }
}

server
{
    listen 127.0.0.1:8081;
    root ./www_eval/site_b;
    index index.html;
    client_max_body_size 512;

    location /
    {
        allowed_methods GET;
        index index.html;
        autoindex off;
    }
}
